
build-package:
  stage: deploy
  image: registry.svleddar-gitlab.leddartech.local/devopsadmin/common_docker_images/gcc-cmake-py3:v1.1
  script:
    - export REQUESTS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"
    - cat $PYPIRC > /tmp/.pypirc
    - pip3 install twine
    - pip3 install --upgrade keyrings.alt 
    - python3 setup.py bdist_wheel sdist
    #- python3 -m twine upload --repository gitlab dist/pioneer_das_api-${CI_COMMIT_TAG}-py3-none-any.whl --config-file /tmp/.pypirc
    - export TWINE_PASSWORD=${CI_JOB_TOKEN}
    - export TWINE_USERNAME=gitlab-ci-token
    - python3 -m twine upload --repository-url https://svleddar-gitlab.leddartech.local/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    #- python3 -m twine upload ./dist/* -u leddartech -p $PYPI_PWD
  only:
    - tags

  artifacts:
    paths:
      - build/sphinx/html/*