name: Sphinx Documentation
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JacksonMaxfield/github-pages-deploy-action-python@master
      env:
        ACCESS_TOKEN: 0a526406b929707b4d5a0b554ad58d4861c5d484
        BASE_BRANCH: master
        BRANCH: master 
        FOLDER: docs/_build/html
        BUILD_SCRIPT: pip install .[all] && make docs-build && touch docs/_build/html/.nojekyll
